import type { Course } from '../types';

export const course: Course = {
  id: 'kulmakerroin',
  title: 'Kulmakerroin',
  locale: 'fi',
  levels: [
    // ── Level 1: Koordinaatisto ───────────────────────────────────────────────
    {
      id: 'koordinaatisto',
      title: 'Koordinaatisto',
      subtitle: 'Pisteiden sijainti tasolla',
      icon: '✕',
      tint: 'var(--color-mint)',
      tintSoft: 'var(--color-mint-soft)',
      shadow: 'var(--color-mint-d)',
      questions: [
        {
          type: 'tap',
          prompt: 'Missä koordinaattiparissa piste P sijaitsee?',
          diagram: 'coord',
          diagramProps: { point: [3, 2], pointLabel: 'P' },
          options: ['(3, 2)', '(2, 3)', '(−3, 2)', '(3, −2)'],
          correct: 0,
          selitys:
            'Ensimmäinen luku on x-koordinaatti (vaakasuunta), toinen on y-koordinaatti (pystysuunta).',
        },
        {
          type: 'match',
          prompt: 'Yhdistä akselit oikeisiin nimiin.',
          diagram: 'coord',
          diagramProps: {},
          targets: ['vaakaakseli', 'pystyakseli'],
          chips: ['x-akseli', 'y-akseli'],
          correct: [0, 1],
          selitys: 'x-akseli on vaakasuora, y-akseli on pystysuora.',
        },
        {
          type: 'tap',
          prompt: 'Missä neljänneksessä piste (−2, 3) sijaitsee?',
          diagram: 'coord',
          diagramProps: {
            point: [-2, 3],
            pointLabel: '',
            highlightQuadrant: 2,
            showQuadrantLabels: true,
          },
          options: ['I', 'II', 'III', 'IV'],
          correct: 1,
          selitys: 'Toisessa neljänneksessä x on negatiivinen ja y on positiivinen.',
        },
        {
          type: 'solve',
          prompt: 'Piste Q on kohdassa (x, y) = (−4, 1). Mikä on x-koordinaatti?',
          options: ['1', '−1', '−4', '4'],
          correct: 2,
          selitys: 'x-koordinaatti on järjestetyn parin ensimmäinen luku: −4.',
        },
        {
          type: 'slider',
          prompt: 'Siirrä pistettä niin, että y-koordinaatti on 3.',
          diagram: 'coord-slider',
          diagramProps: {},
          min: -5,
          max: 5,
          step: 1,
          target: 3,
          tolerance: 0,
          selitys: 'y-koordinaatti 3 tarkoittaa kolme yksikköä x-akselin yläpuolella.',
        },
      ],
    },

    // ── Level 2: Nousu ja juoksu ──────────────────────────────────────────────
    {
      id: 'nousu-juoksu',
      title: 'Nousu ja juoksu',
      subtitle: 'Suoran jyrkkyys visuaalisesti',
      icon: '↗',
      tint: 'var(--color-blue)',
      tintSoft: '#dceaff',
      shadow: 'var(--color-blue-d)',
      questions: [
        {
          type: 'tap',
          prompt: 'Mikä suora on jyrkkin?',
          diagram: 'three-lines',
          diagramProps: {
            lines: [
              { k: 0.5, b: 0, label: 'A', color: 'var(--color-mint)' },
              { k: 2,   b: 0, label: 'B', color: 'var(--color-blue)' },
              { k: 1,   b: 0, label: 'C', color: 'var(--color-gold)' },
            ],
          },
          options: ['A', 'B', 'C', 'Kaikki yhtä jyrkkiä'],
          correct: 1,
          selitys: 'Suoran B kulmakerroin on suurin (k=2), joten se on jyrkkin.',
        },
        {
          type: 'match',
          prompt: 'Yhdistä käsitteet oikeisiin osiin suorasta.',
          diagram: 'rise-run',
          diagramProps: { rise: 3, run: 2 },
          targets: ['pystysuuntainen muutos', 'vaakasuuntainen muutos'],
          chips: ['nousu', 'juoksu'],
          correct: [0, 1],
          selitys: 'Nousu mittaa pystysuuntaisen muutoksen, juoksu vaakasuuntaisen.',
        },
        {
          type: 'tap',
          prompt: 'Suoralla on nousu 4 ja juoksu 2. Onko suora nouseva vai laskeva?',
          diagram: 'rise-run',
          diagramProps: { rise: 4, run: 2 },
          options: ['Nouseva', 'Laskeva', 'Vaakasuora', 'Pystysuora'],
          correct: 0,
          selitys: 'Kun nousu on positiivinen, suora nousee vasemmalta oikealle.',
        },
        {
          type: 'solve',
          prompt: 'Suoran nousu on 6 ja juoksu on 3. Laske kulmakerroin k.',
          diagram: 'rise-run',
          diagramProps: { rise: 6, run: 3 },
          options: ['2', '3', '0.5', '18'],
          correct: 0,
          selitys: 'k = 6 ÷ 3 = 2. Suora nousee kaksi yksikköä jokaista vaakasuoraa yksikköä kohden.',
        },
        {
          type: 'slider',
          prompt: 'Säädä suoran jyrkkyys niin, että kulmakerroin k = 1.',
          diagram: 'gradient-slider',
          diagramProps: { pivot: [0, 0] },
          min: -3,
          max: 3,
          step: 0.1,
          target: 1,
          tolerance: 0.1,
          selitys: 'k = 1 tarkoittaa, että suora nousee täsmälleen 45° kulmassa.',
        },
      ],
    },

    // ── Level 3: Kulmakerroin ─────────────────────────────────────────────────
    {
      id: 'kulmakerroin',
      title: 'Kulmakerroin',
      subtitle: 'k = nousu / juoksu',
      icon: 'k',
      tint: 'var(--color-gold)',
      tintSoft: '#fff2c2',
      shadow: 'var(--color-gold-d)',
      questions: [
        {
          type: 'tap',
          prompt: 'Pisteet A = (1, 2) ja B = (3, 6). Mikä on kulmakerroin?',
          diagram: 'two-point',
          diagramProps: { A: [1, 2], B: [3, 6] },
          options: ['1', '2', '3', '4'],
          correct: 1,
          selitys: 'k = (y₂−y₁)/(x₂−x₁) = (6−2)/(3−1) = 4/2 = 2.',
        },
        {
          type: 'solve',
          prompt: 'Pisteet (0, 0) ja (4, −8). Laske kulmakerroin.',
          options: ['−2', '2', '−0.5', '0.5'],
          correct: 0,
          selitys: 'k = −8/4 = −2. Negatiivinen kulmakerroin tarkoittaa laskevaa suoraa.',
        },
        {
          type: 'tap',
          prompt: 'Suoran kulmakerroin on −3. Miten suora käyttäytyy?',
          options: ['Nousee jyrkästi', 'Laskee jyrkästi', 'On vaakasuora', 'Nousee loivasti'],
          correct: 1,
          selitys: 'Negatiivinen k tarkoittaa laskevaa suoraa. |k| = 3 tarkoittaa jyrkkää laskua.',
        },
        {
          type: 'match',
          prompt: 'Yhdistä kulmakerroin oikeaan suoraan.',
          diagram: 'three-lines',
          diagramProps: {
            lines: [
              { k: -1, b: 0, label: 'A', color: 'var(--color-coral)' },
              { k:  0, b: 0, label: 'B', color: 'var(--color-ink-soft)' },
              { k:  2, b: 0, label: 'C', color: 'var(--color-blue)' },
            ],
          },
          targets: ['A', 'B', 'C'],
          chips: ['k = −1', 'k = 0', 'k = 2'],
          correct: [0, 1, 2],
          selitys: 'k = 0 on vaakasuora, positiivinen k nousee, negatiivinen laskee.',
        },
        {
          type: 'slider',
          prompt: 'Säädä suoran jyrkkyys niin, että kulmakerroin on tarkalleen 3.',
          diagram: 'gradient-slider',
          diagramProps: { pivot: [0, 0] },
          min: -4,
          max: 4,
          step: 0.5,
          target: 3,
          tolerance: 0.15,
          selitys: 'k = 3 tarkoittaa nousua 3 yksikköä jokaista vaakasuoraa yksikköä kohden.',
        },
      ],
    },

    // ── Level 4: Y-leikkauspiste ──────────────────────────────────────────────
    {
      id: 'y-leikkauspiste',
      title: 'Y-leikkauspiste',
      subtitle: 'Missä suora leikkaa y-akselin?',
      icon: 'b',
      tint: 'var(--color-violet)',
      tintSoft: '#ece1ff',
      shadow: 'var(--color-violet-d)',
      questions: [
        {
          type: 'tap',
          prompt: 'Missä kohdassa suora y = 2x + 4 leikkaa y-akselin?',
          diagram: 'linear',
          diagramProps: { k: 2, b: 4 },
          options: ['(0, 2)', '(0, 4)', '(4, 0)', '(2, 0)'],
          correct: 1,
          selitys: 'Y-leikkauspiste on aina muotoa (0, b). Tässä b = 4, joten piste on (0, 4).',
        },
        {
          type: 'solve',
          prompt: 'Suora kulkee pisteen (0, −3) kautta, kulmakerroin on 1. Mikä on b?',
          options: ['−3', '3', '1', '−1'],
          correct: 0,
          selitys: 'Kun x = 0, y = b suoraan. Joten b = −3.',
        },
        {
          type: 'slider',
          prompt: 'Siirrä suoraa ylös tai alas niin, että se leikkaa y-akselin kohdassa y = 2.',
          diagram: 'linear-shift',
          diagramProps: { k: 1 },
          min: -5,
          max: 5,
          step: 0.5,
          target: 2,
          tolerance: 0.1,
          selitys: 'Muuttamalla b:tä siirrät suoraa ylös tai alas muuttamatta sen jyrkkyyttä.',
        },
        {
          type: 'match',
          prompt: 'Yhdistä yhtälö oikeaan y-leikkauspisteeseen.',
          targets: ['y = x + 3', 'y = 2x − 1', 'y = −x + 5'],
          chips: ['(0, 3)', '(0, −1)', '(0, 5)'],
          correct: [0, 1, 2],
          selitys: 'Y-leikkauspiste saadaan suoraan vakiotermistä b yhtälössä y = kx + b.',
        },
        {
          type: 'tap',
          prompt: 'Mikä yhtälö sopii suoralle, jonka y-leikkauspiste on (0, −2) ja kulmakerroin 3?',
          options: ['y = 2x − 3', 'y = 3x − 2', 'y = −2x + 3', 'y = 3x + 2'],
          correct: 1,
          selitys: 'k = 3 ja b = −2, joten y = 3x + (−2) = 3x − 2.',
        },
      ],
    },

    // ── Level 5: Lineaarinen yhtälö ───────────────────────────────────────────
    {
      id: 'lineaarinen-yhtalo',
      title: 'Lineaarinen yhtälö',
      subtitle: 'y = kx + b kokonaan',
      icon: 'y=',
      tint: 'var(--color-coral)',
      tintSoft: '#ffd9d9',
      shadow: 'var(--color-coral-d)',
      questions: [
        {
          type: 'tap',
          prompt: 'Mikä on suoran y = −2x + 5 kulmakerroin ja y-leikkauspiste?',
          diagram: 'linear',
          diagramProps: { k: -2, b: 5 },
          options: ['k=5, b=−2', 'k=−2, b=5', 'k=2, b=5', 'k=−2, b=−5'],
          correct: 1,
          selitys: 'Muodossa y = kx + b: k on x:n kerroin (−2) ja b on vakiotermi (5).',
        },
        {
          type: 'solve',
          prompt: 'Suora kulkee pisteiden (1, 3) ja (3, 7) kautta. k = 2. Mikä on b?',
          options: ['b = 1', 'b = 2', 'b = 3', 'b = −1'],
          correct: 0,
          selitys: 'Sijoitetaan piste (1, 3): 3 = 2·1 + b → b = 1. Yhtälö on y = 2x + 1.',
        },
        {
          type: 'match',
          prompt: 'Yhdistä yhtälö oikeaan kuvaajaan.',
          diagram: 'three-lines',
          diagramProps: {
            lines: [
              { k:  1, b: 1, label: 'A', color: 'var(--color-mint)' },
              { k: -1, b: 3, label: 'B', color: 'var(--color-coral)' },
              { k:  2, b: 0, label: 'C', color: 'var(--color-blue)' },
            ],
          },
          targets: ['Suora A', 'Suora B', 'Suora C'],
          chips: ['y = x + 1', 'y = −x + 3', 'y = 2x'],
          correct: [0, 1, 2],
          selitys:
            'Vertaa kulmakerrointa (jyrkkyys/suunta) ja y-leikkauspistettä (missä leikkaa y-akselin).',
        },
        {
          type: 'dual-slider',
          prompt:
            'Säädä kulmakerroin ja y-leikkauspiste niin, että suora kulkee pisteiden (0, 1) ja (2, 5) kautta.',
          diagram: 'linear',
          diagramProps: { targetPoints: [[0, 1], [2, 5]] },
          sliders: [
            { label: 'k', min: -3, max: 4, step: 0.5, target: 2, tolerance: 0.15 },
            { label: 'b', min: -3, max: 4, step: 0.5, target: 1, tolerance: 0.15 },
          ],
          selitys: 'k = (5−1)/(2−0) = 2 ja b = 1. Yhtälö on y = 2x + 1.',
        },
        {
          type: 'tap',
          prompt: 'Missä kohdassa suora y = 3x − 6 leikkaa x-akselin?',
          options: ['x = 2', 'x = 3', 'x = 6', 'x = −2'],
          correct: 0,
          selitys: 'X-leikkauspiste: aseta y = 0 → 0 = 3x − 6 → x = 2.',
        },
      ],
    },
  ],
};
