import type { Course } from '../types';

export const course: Course = {
  id: 'kulmakerroin',
  title: 'Kulmakerroin',
  locale: 'fi',
  levels: [
    {
      id: 'koordinaatisto',
      title: 'Koordinaatisto',
      subtitle: 'Pisteiden sijainti tasolla',
      icon: '✕',
      tint: 'var(--color-mint)',
      tintSoft: 'var(--color-mint-soft)',
      shadow: 'var(--color-mint-d)',
      questions: [
        {
          type: 'tap',
          prompt: 'Missä koordinaattiparissa piste P sijaitsee?',
          diagram: 'coord',
          diagramProps: { point: [3, 2], pointLabel: 'P' },
          options: ['(3, 2)', '(2, 3)', '(−3, 2)', '(3, −2)'],
          correct: 0,
          selitys:
            'Ensimmäinen luku on x-koordinaatti (vaakasuunta), toinen on y-koordinaatti (pystysuunta).',
        },
        {
          type: 'match',
          prompt: 'Yhdistä akselit oikeisiin nimiin.',
          diagram: 'coord',
          diagramProps: {},
          targets: ['vaakaakseli', 'pystyakseli'],
          chips: ['x-akseli', 'y-akseli'],
          correct: [0, 1],
          selitys: 'x-akseli on vaakasuora, y-akseli on pystysuora.',
        },
        {
          type: 'tap',
          prompt: 'Missä neljänneksessä piste (−2, 3) sijaitsee?',
          diagram: 'coord',
          diagramProps: {
            point: [-2, 3],
            pointLabel: '',
            highlightQuadrant: 2,
            showQuadrantLabels: true,
          },
          options: ['I', 'II', 'III', 'IV'],
          correct: 1,
          selitys: 'Toisessa neljänneksessä x on negatiivinen ja y on positiivinen.',
        },
        {
          type: 'solve',
          prompt: 'Piste Q on kohdassa (x, y) = (−4, 1). Mikä on x-koordinaatti?',
          options: ['1', '−1', '−4', '4'],
          correct: 2,
          selitys: 'x-koordinaatti on järjestetyn parin ensimmäinen luku: −4.',
        },
        {
          type: 'slider',
          prompt: 'Siirrä pistettä niin, että y-koordinaatti on 3.',
          diagram: 'coord-slider',
          diagramProps: {},
          min: -5,
          max: 5,
          step: 1,
          target: 3,
          tolerance: 0,
          selitys: 'y-koordinaatti 3 tarkoittaa kolme yksikköä x-akselin yläpuolella.',
        },
      ],
    },
    {
      id: 'nousu-juoksu',
      title: 'Nousu ja juoksu',
      subtitle: 'Suoran jyrkkyys visuaalisesti',
      icon: '↗',
      tint: 'var(--color-blue)',
      tintSoft: '#dceaff',
      shadow: 'var(--color-blue-d)',
      questions: [],
    },
    {
      id: 'kulmakerroin',
      title: 'Kulmakerroin',
      subtitle: 'k = nousu / juoksu',
      icon: 'k',
      tint: 'var(--color-gold)',
      tintSoft: '#fff2c2',
      shadow: 'var(--color-gold-d)',
      questions: [],
    },
    {
      id: 'y-leikkauspiste',
      title: 'Y-leikkauspiste',
      subtitle: 'Missä suora leikkaa y-akselin?',
      icon: 'b',
      tint: 'var(--color-violet)',
      tintSoft: '#ece1ff',
      shadow: 'var(--color-violet-d)',
      questions: [],
    },
    {
      id: 'lineaarinen-yhtalo',
      title: 'Lineaarinen yhtälö',
      subtitle: 'y = kx + b kokonaan',
      icon: 'y=',
      tint: 'var(--color-coral)',
      tintSoft: '#ffd9d9',
      shadow: 'var(--color-coral-d)',
      questions: [],
    },
  ],
};
